apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-catalog-2
  labels:
    app: videos-catalog-2
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: videos-catalog-2
  template:
    metadata:
      labels:
        app: videos-catalog-2
    spec:
      containers:
        - name: videos-catalog-2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
          image: soeirosantos/videos-catalog
          imagePullPolicy: Always
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: videos-catalog-2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  backend:
    serviceName: videos-catalog-2
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: videos-catalog-2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: videos-catalog-2
